Layout
Young-Gaius/react-magic pull request #2
Opened 2023-08-15 20:42 UTC by Young-Gaius

In this milestone, I did the following:

Deleted all the boilerplate from Create React App (text, images, styles).
Created a new directory called Components.
Inside components, created a new Calculator.js file.

2023-08-15 20:59 UTC, DammyShittu requested changes
Hi @Young-Gaius,

## Highlights
✔️ Deleting generated files

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-15 20:59 UTC, DammyShittu commented on src/components/Calculator.js
> +);
- [ ] The Calculator component should have at least one child component. Kindly add this component.

2023-08-15 20:59 UTC, DammyShittu commented on src/components/Calculator.js
> +      <button type="button" className="operator">+</button>
- [ ] You have two plus signs. This should be &div; as contained in the design.

2023-08-15 20:59 UTC, DammyShittu commented on src/components/Calculator.js
> +const Calculator = () => (
- [ ] Your design should match the one provided. Kindly redesign the UI to match the design. It is important as front-end developers that we learn to stick to the provided designs.

  Your Implementation | Figma Design
  :---:|:---:
  ![image](https://github.com/Young-Gaius/react-magic/assets/54848363/982b26e7-0c6f-40a6-af3f-a25b864552f2) | ![image](https://github.com/Young-Gaius/react-magic/assets/54848363/b7c7e8a2-439d-4c7f-9658-9694aa0f74e6)

2023-08-17 15:24 UTC, frank1738 requested changes
Hi @Young-Gaius , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ calculator is designed as expected 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 15:24 UTC, frank1738 commented on src/components/Button.js
> +export default Button;
- [ ] 👋 Hey there! 😄 Just a friendly heads-up – I noticed you crafted a cool subcomponent (button) for the calculator, but it's not being used in the main component. Let's get that subcomponent shining by importing and integrating it. This way, we'll boost efficiency and maintainability. Keep up the awesome work! 💪😄

2023-08-17 17:55 UTC, gemmen29 approved these changes
Hi @Young-Gaius, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 17:21 UTC, merged